import { describe, expect, it } from "vitest"

import { readSource } from "../helpers/source"

const switcher = readSource("components", "deck-switcher.tsx")
const tools = readSource("components", "deck-tools-panel.tsx")
const sheet = readSource("components", "ui", "sheet.tsx")
const shell = readSource("components", "app-shell.tsx")

describe("卡包 sheet chrome", () => {
  it("keeps the list as one 卡包 bottom Sheet and uses Dialog / AlertDialog for writes", () => {
    expect(switcher).toContain('side="bottom"')
    expect(switcher).toMatch(/<SheetTitle[^>]*>卡包<\/SheetTitle>/)
    expect(switcher).toContain("改名")
    expect(switcher).toContain("复制")
    expect(switcher).toContain("删除")
    expect(switcher).toContain("新建")
    expect(switcher).toContain('aria-label="更多"')
    expect(switcher).not.toContain("管理卡包")
    expect(switcher).not.toContain("卡包管理")
    expect(switcher).not.toContain("当前：")
    expect(switcher).toContain('from "@/components/ui/dialog"')
    expect(switcher).toContain("AlertDialog")
    expect(switcher).toContain("showCloseButton={false}")
    expect(switcher).not.toContain('data-slot="deck-nested-sheet"')
    expect(switcher).not.toContain("fixed inset-0 z-[80]")
    expect(switcher).not.toContain("<SheetTitle>{nestedTitle}</SheetTitle>")
    expect(switcher).toContain('kind: "duplicate"')
    expect(switcher).toContain("nextCopyDeckName")
    expect(switcher).toContain("startNameStep")
    expect(switcher).toContain("onDuplicate(step.entry.id, name)")
    expect(switcher).not.toContain("onDuplicate(entry.id)")
    expect(switcher).toContain("onSelect={(event) => {")
    expect(switcher).toContain("event.preventDefault()")
    expect(switcher).toContain("确定删除「")
    expect(switcher).toContain("本机数据无法恢复。")
    expect(switcher).toContain("onEscapeKeyDown={(event) => event.preventDefault()}")
    expect(switcher).toContain("onInteractOutside={blockSheetDismiss}")
    expect(switcher).toContain("if (!next && step) return")
    expect(switcher.match(/<Sheet[\s>]/g)?.length ?? 0).toBe(1)
    expect(sheet).toContain("z-[70]")
    expect(shell).toContain('aria-label="主要导航"')
    expect(shell).toContain("z-50")
    expect(shell).toContain("grid-cols-3")
  })

  it("does not keep a 管理卡包 row on the 卡包 settings list", () => {
    expect(tools).toContain("DECK_TEMPLATES_LABEL")
    expect(tools).toContain("PATHS.settingsTemplates")
    expect(tools).toContain("导入")
    expect(tools).toContain("导出")
    expect(tools).not.toContain("管理卡包")
    expect(tools).not.toContain("推送到 Anki")
  })
})
